name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # täglich 00:00 UTC
  workflow_dispatch:

# WICHTIG: Schreibrechte, damit in den Branch "output" gepusht werden kann
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SVG
        uses: Platane/snk@v3
        with:
          github_user_name: stoicfist
          # Dark-Palette via Query-Param
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
