name: Generate Snake

on:
  schedule: # alle 24h aktualisieren
    - cron: "0 0 * * *"
  workflow_dispatch: # manuell starten

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: stoicfist
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
